Feito model result
talDoFlemis/bentomark-2 pull request #5
Opened 2023-12-02 21:38 UTC by Alanzcc

Por algum motivo mesmo eu selecionando o que eu queria dar add ele puxou tudo. então dps a gente passa so o que impota, mas ta ai eu fiz no model.hpp model.cpp Model_Request.hpp Model_Request.cpp

2023-12-02 21:49 UTC, talDoFlemis requested changes

2023-12-02 21:49 UTC, talDoFlemis commented on .vscode/settings.json
fazer o gitignore desse arquivo

2023-12-02 21:49 UTC, talDoFlemis commented on build/.cmake/api/v1/query/client-vscode/query.json
Fazer o gitignore dessa pasta build inteira

2023-12-02 21:49 UTC, talDoFlemis commented on libs/models/include/model.hpp
> +#include "Model_Result.hpp"
esse include não irá funcionar pq você não está usando as pastas dele seria algo como models/include/Model_Result

2023-12-02 21:49 UTC, talDoFlemis commented on libs/models/include/model.hpp
> +  void get_model_result(const Algebra::Vector &vec1, const Algebra::Vector &vec2);
funções get normalmente retornam valores, funções set são as que usam void

[Encapsulacao](https://www.w3schools.com/cpp/cpp_encapsulation.asp)

2023-12-02 22:37 UTC, Alanzcc reviewed
Agora vai salidummmm

2023-12-03 10:41 UTC, talDoFlemis approved these changes

2023-12-03 14:10 UTC, merged